  create table usuario (
        id bigint generated by default as identity,
        nome varchar(255),
        email varchar(255),
        senha varchar(255),
        primary key (id)
    );
    
    
  create table funcao (
        id bigint generated by default as identity,
        nome enum ('ADMIN','COORDENADOR','DIRETOR','DISCENTE','PROFESSOR','SERVICOS','SUPORTE'),
        primary key (id)
    );
