-- DROP TABELAS
DROP TABLE IF EXISTS usuario_setor_tab CASCADE;
DROP TABLE IF EXISTS usuario_funcao_tab CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS pessoa CASCADE;
DROP TABLE IF EXISTS setor CASCADE;
DROP TABLE IF EXISTS funcao CASCADE;
