-- Criar tabela funcao
CREATE TABLE funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome ENUM('GERENTE','AUXILIAR','OPERADOR'),
    PRIMARY KEY (id)
);

-- Criar tabela setor
CREATE TABLE setor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50),
    PRIMARY KEY (id)
);

-- Criar tabela pessoa
CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(80) NOT NULL,
    cpf VARCHAR(255),
    data_nascimento DATE,
    email VARCHAR(255),
    PRIMARY KEY (id)
);

-- Criar tabela usuario
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    senha VARCHAR(255),
    PRIMARY KEY (id)
);

-- Tabelas de relacionamento
CREATE TABLE usuario_funcao_tab (
    id_usuario BIGINT NOT NULL,
    id_funcao BIGINT NOT NULL,
    PRIMARY KEY (id_funcao, id_usuario)
);

CREATE TABLE usuario_setor_tab (
    id_usuario BIGINT NOT NULL,
    id_setor BIGINT NOT NULL,
    PRIMARY KEY (id_setor, id_usuario)
);
