
    
    create table funcao (
        id bigint generated by default as identity,
        nome enum ('GERENTE','AUXILIAR','OPERADOR'),
        primary key (id)
    );

    create table pessoa (
        data_nascimento date,
        id bigint generated by default as identity,
        nome varchar(80) not null,
        cpf varchar(255),
        email varchar(255),
        primary key (id)
    );
    
    create table usuario (
        id bigint generated by default as identity,
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );
    
    create table usuario_funcao_tab (
        id_funcao bigint not null,
        id_usuario bigint not null,
        primary key (id_funcao, id_usuario)
    );